# Sidebar navigation

- label: "Introduction"
  link: /
- label: "Getting Started"
  link: /getting-started
- label: Setup
  items:
    - label: "Setting up WordPress"
      link: "/setup/wp"
    - label: "Installing Gatsby Starter"
      link: "/setup/install"
    - label: "Setting up Gatsby"
      link: "/setup/gatsby"
- label: Configuration
  items:
    - label: "WordPress Core Settings"
      link: "/configuration/wp-core"
    - label: "WordPress Theme Options"
      link: "/configuration/wp"
    - label: "Gatsby config.js"
      link: "/configuration/gatsby-config"
    - label: "Colors Configuration"
      link: "/configuration/colors"

- label: Features
  items:
    - label: "Contact Forms"
      link: "/features/contact-forms"
    - label: Galleries
      link: /features/galleries
    - label: "Code Highlighting"
      link: /features/code-highlighting
- label: More
  items:
    - label: "Overriding WP options"
      link: "/more/override-wp"

- label: Links
  items:
    - label: "gatsbywpthemes.com"
      link: https://gatsbywpthemes.com
    - label: "Gatsby Documentation"
      link: https://gatsbyjs.com
