# Sidebar navigation

- label: "Introduction"
  link: /
- label: "Getting Started"
  link: /getting-started
- label: Setup
  items:
    - label: "Setting Up WordPress"
      link: "/setup/wp"
    - label: "Setting Up Gatsby"
      link: "/setup/gatsby"
- label: Configuration
  items:
    - label: "WordPress Core Settings"
      link: "/configuration/wp-core"
    - label: "WordPress Theme Options"
      link: "/configuration/wp"
    - label: "Gatsby config.js"
      link: "/configuration/gatsby-config"

- label: Features
  items:
    - label: "Contact Forms"
      link: "/features/contact-forms"
    - label: Galleries
      link: /features/galleries
    - label: "Code Highlighting"
      link: /features/code-highlighting
- label: More
  items:
    - label: "Overriding WP options"
      link: "/more/override-wp"

- label: Links
  items:
    - label: "gatsbywpthemes.com"
      link: https://gatsbywpthemes.com
    - label: FAQ
      link: https://gatsbywpthemes.com/faq
    - label: "Gatsby Documentation"
      link: https://gatsbyjs.com
